version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `swimstep` directory
    directory: "/swimstep"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Limit to 10 open pull requests for version updates
    open-pull-requests-limit: 10
    # Group all minor and patch updates together
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    # Limit to 5 open pull requests for version updates
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
